### ISSUE TITLE
No negative value reading?

### ISSUE THREAD

**Issue by beicnet** [xreef/DHT12_sensor_library#1]
Hi there,

I really like your project and library, but my issue is that I can't get negative measurement value when reading the sensor output.

In a room environment everything seems to be good as I see, but if I put the sensor outdoor I got really weird readings:
```
- DHT 12 (i2c)
Status: Ok
Temperature: 13.50 c
Humidity: 95.00 %
```
and here is the readings from our local weather station (about 300-400m from my house):
```
Temperature: -0.70 c
Humidity: 96.00 %
```
Tested 12pcs DHT12 sensors (brand new ones), I tought that was defective, but I got the same results with all of them.

Using WeMos D1 mini, Arduino IDE v1.8.2, ESP8266 Core v2.3.0.

Thank you for your answer! :wink: 

Kind regards,
Viktor

**Comment by xreef** [comment]
Hi Viktor,
How much was the outside temperature when you got this result?
Do You use onewire or i2c comunication?
What is the supply voltage in and out?
Thanks

**Comment by beicnet** [comment]
Hi @xreef,

Thank you for your reply! ;)

1. Outside temperature was -0.70 c (as I wrote above)
2. I used over i2c bus (as I wrote above)
3. 4.95v wall adapter and sensor is powered from 3.3v

Regards,
Viktor

**Comment by xreef** [comment]
I mean the real external temperature, but you use the same wall adapter in the weather station? 
And you use the pin to supply voltage to the sensor? or external adapter?
It's important that voltage is well stabilized and give sufficient amperage.

**Comment by beicnet** [comment]
The real external temperature is measured by our loacal weather station and not by me.
The wall adapter is capable of giving a straight/continious 500mA amperage.
The sensor is powered by the WeMos D1 mini dual base.

**Comment by xreef** [comment]
I need to know the real temperature, not the wrong temperature measured, to recreate the test case.

Try a test: power the sensor to an external power supply (with share ground with d1). As you can see in the breadboard schema I use an external power supply, not the supply from d1.

**Comment by beicnet** [comment]
Ok, I can do that for you, but at the moment it's not possible, because it's worm again outside...
The weird thing is that it measuring is good at the room temperature, but outside when it's bellow zero, it's shows me +13.50c and it should -0.70c...

**Comment by beicnet** [comment]
Also I noticed when the sensor reached the 95% of humidity level and the temperature went bellow zero, the sensor reding flipped to +13.50c for some reason...

But, I will do it like you proposed...

btw...did you tested your project bellow zero?

**Comment by xreef** [comment]
I try to test It in my fridge as soon as possible.

**Comment by xreef** [comment]
Hi,
I tested the problem, I have to take the sign from the third byte of data, and exclude it from value.

I create an Instructable to test this
https://www.instructables.com/id/Arduino-Remotewireless-Programming-and-Test-With-H/

Now I try to fix.
