### ISSUE TITLE
Incorrect moisture readings

### ISSUE THREAD

**Issue by noxmyn** [xreef/DHT12_sensor_library#10]
Temperature readings coincide with other devices in the house: split system, xiaomi sensors.

But humidity indicators are greatly underestimated. At an actual 39-40 percent, the sensor outputs 21-24 percent.
Test 2 different HDT12 sensors, the deviation is the same.

**Comment by xreef** [comment]
Hi noxmin,
I do a comparative here
https://www.mischianti.org/2019/07/16/temperature-humidity-sensors-comparison-data-part-3/

And the result was good.

Pay attention to resistor, voltage and the lenght of wiring.
It's important to take sensor free also.

Bye Renzo

**Comment by noxmyn** [comment]
I connect to esp8266, 1-wire according to the correct scheme, including a 10 kilo-ohm resistor.

**Comment by xreef** [comment]
Can be a lot of reason, It's possible also that are fake cina clone.
Not related to the library.
Bye Renzo
