### ISSUE TITLE
Wemos D1 Mini + DHT12 I2C Shield + DHT12_sensor_library

### ISSUE THREAD

**Issue by mwilfried** [xreef/DHT12_sensor_library#4]
Hello 

I'm newbie and trying to use the library with my wemos d1 mini and its DHT12 shield soldered.

Actually with the default configuration, I 've got an error and I can't read the DHT12 sensor.

According to wemos :
 * The WeMos D1 Mini I2C bus uses pins:
 * D1 = SCL
 * D2 = SDA

How can I check that there are used by the library or that force the library to use them ?

Thanks

**Comment by xreef** [comment]
Hi,
mmmm... can you explain the error?
I retry to connect my D1 Wemos, but work correctly, please add the schema (a photo also is ok).
Check [schema connection](https://www.mischianti.org/2019/01/01/dht12-library-en/), you can add this information [here ](https://www.mischianti.org/forum/forum/xreef-dht12_sensor_library/)also.
Thanks

**Comment by mwilfried** [comment]
I've got an error message :  "Failed to read from the DHT12 sensor"
And all seems to be well connected.

Here the photo of my shields

**Comment by mwilfried** [comment]
I've got an error message :  "Failed to read from the DHT12 sensor"
And all seems to be well connected to : 
- 3v3
- Ground
- D1
- D2
Is there any need to change the address section ? 
DHT12 dht12(uint8_t addressOrPin)
Can you give an example ?

**Comment by xreef** [comment]
Hi,
i can't see the photo, try to use an i2cScanner https://playground.arduino.cc/Main/I2cScanner than try to add external power source.
Try to repost schema 
Thanks

**Comment by mwilfried** [comment]
Here the picture
![img_20190108_182916](https://user-images.githubusercontent.com/32105900/50908724-9acfc380-142a-11e9-9e24-1af18476bbc3.jpg)

Here the I2C Scanner output

16:19:01.860 -> I2C Scanner to scan for devices on each port pair D0 to D7
16:19:01.860 -> Scanning (SDA : SCL) - D0 : D1 - No I2C devices found
16:19:01.860 -> Scanning (SDA : SCL) - D0 : D2 - No I2C devices found
16:19:01.927 -> Scanning (SDA : SCL) - D0 : D3 - No I2C devices found
16:19:01.927 -> Scanning (SDA : SCL) - D0 : D4 - No I2C devices found
16:19:01.960 -> Scanning (SDA : SCL) - D0 : D5 - No I2C devices found
16:19:01.960 -> Scanning (SDA : SCL) - D0 : D6 - No I2C devices found
16:19:01.993 -> Scanning (SDA : SCL) - D0 : D7 - No I2C devices found
16:19:01.993 -> Scanning (SDA : SCL) - D1 : D0 - No I2C devices found
16:19:02.026 -> Scanning (SDA : SCL) - D1 : D2 - No I2C devices found
16:19:02.059 -> Scanning (SDA : SCL) - D1 : D3 - No I2C devices found
16:19:02.059 -> Scanning (SDA : SCL) - D1 : D4 - No I2C devices found
16:19:02.092 -> Scanning (SDA : SCL) - D1 : D5 - No I2C devices found
16:19:02.092 -> Scanning (SDA : SCL) - D1 : D6 - No I2C devices found
16:19:02.126 -> Scanning (SDA : SCL) - D1 : D7 - No I2C devices found
16:19:02.126 -> Scanning (SDA : SCL) - D2 : D0 - I2C device found at address 0x05  !
16:19:02.126 -> I2C device found at address 0x06  !
16:19:02.159 -> Unknow error at address 0x07
16:19:02.159 -> I2C device found at address 0x0A  !
16:19:02.159 -> I2C device found at address 0x0F  !
16:19:02.159 -> I2C device found at address 0x13  !
16:19:02.159 -> I2C device found at address 0x18  !
16:19:02.159 -> Unknow error at address 0x1E
16:19:02.159 -> I2C device found at address 0x22  !
16:19:02.159 -> I2C device found at address 0x27  !
16:19:02.159 -> I2C device found at address 0x2C  !
16:19:02.159 -> I2C device found at address 0x32  !
16:19:02.159 -> I2C device found at address 0x38  !
16:19:02.192 -> I2C device found at address 0x3F  !
16:19:02.192 -> I2C device found at address 0x43  !
16:19:02.192 -> I2C device found at address 0x48  !
16:19:02.192 -> I2C device found at address 0x4D  !
16:19:02.192 -> Unknow error at address 0x53
16:19:02.192 -> I2C device found at address 0x58  !
16:19:02.192 -> Unknow error at address 0x60
16:19:02.192 -> I2C device found at address 0x64  !
16:19:02.192 -> I2C device found at address 0x6A  !
16:19:02.192 -> I2C device found at address 0x71  !
16:19:02.192 -> I2C device found at address 0x78  !
16:19:02.225 -> **********************************
16:19:02.225 -> 
16:19:02.225 -> Scanning (SDA : SCL) - D2 : D1 - I2C device found at address 0x05  !
16:19:02.225 -> I2C device found at address 0x09  !
16:19:02.225 -> I2C device found at address 0x0E  !
16:19:02.225 -> I2C device found at address 0x12  !
16:19:02.225 -> I2C device found at address 0x17  !
16:19:02.225 -> I2C device found at address 0x1C  !
16:19:02.225 -> I2C device found at address 0x21  !
16:19:02.225 -> Unknow error at address 0x26
16:19:02.225 -> Unknow error at address 0x2B
16:19:02.258 -> I2C device found at address 0x30  !
16:19:02.258 -> I2C device found at address 0x35  !
16:19:02.258 -> I2C device found at address 0x3B  !
16:19:02.258 -> I2C device found at address 0x41  !
16:19:02.258 -> I2C device found at address 0x45  !
16:19:02.258 -> I2C device found at address 0x4A  !
16:19:02.258 -> I2C device found at address 0x50  !
16:19:02.258 -> I2C device found at address 0x55  !
16:19:02.258 -> I2C device found at address 0x5B  !
16:19:02.258 -> I2C device found at address 0x61  !
16:19:02.292 -> Unknow error at address 0x67
16:19:02.292 -> I2C device found at address 0x6C  !
16:19:02.292 -> I2C device found at address 0x73  !
16:19:02.292 -> I2C device found at address 0x7A  !
16:19:02.292 -> **********************************
16:19:02.292 -> 
16:19:02.292 -> Scanning (SDA : SCL) - D2 : D3 - I2C device found at address 0x05  !
16:19:02.292 -> I2C device found at address 0x09  !
16:19:02.292 -> I2C device found at address 0x0E  !
16:19:02.292 -> I2C device found at address 0x12  !
16:19:02.292 -> I2C device found at address 0x17  !
16:19:02.325 -> I2C device found at address 0x1C  !
16:19:02.325 -> I2C device found at address 0x21  !
16:19:02.325 -> I2C device found at address 0x26  !
16:19:02.325 -> I2C device found at address 0x2B  !
16:19:02.325 -> I2C device found at address 0x31  !
16:19:02.325 -> I2C device found at address 0x36  !
16:19:02.325 -> Unknow error at address 0x3D
16:19:02.325 -> I2C device found at address 0x42  !
16:19:02.325 -> I2C device found at address 0x47  !
16:19:02.325 -> I2C device found at address 0x4C  !
16:19:02.358 -> Unknow error at address 0x52
16:19:02.358 -> Unknow error at address 0x58
16:19:02.358 -> I2C device found at address 0x5E  !
16:19:02.358 -> Unknow error at address 0x64
16:19:02.358 -> Unknow error at address 0x6A
16:19:02.358 -> I2C device found at address 0x70  !
16:19:02.358 -> I2C device found at address 0x77  !
16:19:02.358 -> **********************************
16:19:02.358 -> 
16:19:02.358 -> Scanning (SDA : SCL) - D2 : D4 - I2C device found at address 0x05  !
16:19:02.358 -> I2C device found at address 0x09  !
16:19:02.358 -> I2C device found at address 0x0E  !
16:19:02.391 -> I2C device found at address 0x12  !
16:19:02.391 -> I2C device found at address 0x17  !
16:19:02.391 -> I2C device found at address 0x1C  !
16:19:02.391 -> I2C device found at address 0x21  !
16:19:02.391 -> Unknow error at address 0x26
16:19:02.391 -> Unknow error at address 0x2B
16:19:02.391 -> I2C device found at address 0x30  !
16:19:02.391 -> I2C device found at address 0x35  !
16:19:02.391 -> I2C device found at address 0x3B  !
16:19:02.391 -> I2C device found at address 0x41  !
16:19:02.424 -> I2C device found at address 0x45  !
16:19:02.424 -> I2C device found at address 0x4A  !
16:19:02.424 -> I2C device found at address 0x50  !
16:19:02.424 -> I2C device found at address 0x55  !
16:19:02.424 -> I2C device found at address 0x5B  !
16:19:02.424 -> I2C device found at address 0x61  !
16:19:02.424 -> I2C device found at address 0x66  !
16:19:02.424 -> I2C device found at address 0x6C  !
16:19:02.424 -> Unknow error at address 0x73
16:19:02.424 -> I2C device found at address 0x79  !
16:19:02.457 -> **********************************
16:19:02.457 -> 
16:19:02.457 -> Scanning (SDA : SCL) - D2 : D5 - I2C device found at address 0x05  !
16:19:02.457 -> I2C device found at address 0x09  !
16:19:02.457 -> I2C device found at address 0x0E  !
16:19:02.457 -> I2C device found at address 0x12  !
16:19:02.457 -> I2C device found at address 0x17  !
16:19:02.457 -> I2C device found at address 0x1C  !
16:19:02.457 -> I2C device found at address 0x21  !
16:19:02.457 -> Unknow error at address 0x26
16:19:02.457 -> Unknow error at address 0x2B
16:19:02.457 -> I2C device found at address 0x30  !
16:19:02.491 -> I2C device found at address 0x35  !
16:19:02.491 -> I2C device found at address 0x3B  !
16:19:02.491 -> I2C device found at address 0x41  !
16:19:02.491 -> I2C device found at address 0x45  !
16:19:02.491 -> I2C device found at address 0x4A  !
16:19:02.491 -> I2C device found at address 0x50  !
16:19:02.491 -> I2C device found at address 0x55  !
16:19:02.491 -> I2C device found at address 0x5B  !
16:19:02.491 -> I2C device found at address 0x61  !
16:19:02.524 -> I2C device found at address 0x66  !
16:19:02.524 -> I2C device found at address 0x6C  !
16:19:02.524 -> Unknow error at address 0x73
16:19:02.524 -> I2C device found at address 0x79  !
16:19:02.524 -> **********************************
16:19:02.524 -> 
16:19:02.524 -> Scanning (SDA : SCL) - D2 : D6 - I2C device found at address 0x05  !
16:19:02.524 -> I2C device found at address 0x09  !
16:19:02.524 -> I2C device found at address 0x0E  !
16:19:02.524 -> I2C device found at address 0x12  !
16:19:02.524 -> I2C device found at address 0x17  !
16:19:02.557 -> I2C device found at address 0x1C  !
16:19:02.557 -> I2C device found at address 0x21  !
16:19:02.557 -> Unknow error at address 0x26
16:19:02.557 -> Unknow error at address 0x2B
16:19:02.557 -> I2C device found at address 0x30  !
16:19:02.557 -> I2C device found at address 0x35  !
16:19:02.557 -> I2C device found at address 0x3B  !
16:19:02.557 -> I2C device found at address 0x41  !
16:19:02.557 -> I2C device found at address 0x45  !
16:19:02.557 -> I2C device found at address 0x4A  !
16:19:02.557 -> I2C device found at address 0x50  !
16:19:02.557 -> I2C device found at address 0x55  !
16:19:02.590 -> I2C device found at address 0x5B  !
16:19:02.590 -> I2C device found at address 0x61  !
16:19:02.590 -> I2C device found at address 0x66  !
16:19:02.590 -> I2C device found at address 0x6C  !
16:19:02.590 -> Unknow error at address 0x73
16:19:02.590 -> I2C device found at address 0x79  !
16:19:02.590 -> **********************************
16:19:02.590 -> 
16:19:02.590 -> Scanning (SDA : SCL) - D2 : D7 - I2C device found at address 0x05  !
16:19:02.590 -> I2C device found at address 0x09  !
16:19:02.623 -> I2C device found at address 0x0E  !
16:19:02.623 -> I2C device found at address 0x12  !
16:19:02.623 -> I2C device found at address 0x17  !
16:19:02.623 -> I2C device found at address 0x1C  !
16:19:02.623 -> I2C device found at address 0x21  !
16:19:02.623 -> Unknow error at address 0x26
16:19:02.623 -> Unknow error at address 0x2B
16:19:02.623 -> I2C device found at address 0x30  !
16:19:02.623 -> I2C device found at address 0x35  !
16:19:02.623 -> I2C device found at address 0x3B  !
16:19:02.657 -> I2C device found at address 0x41  !
16:19:02.657 -> I2C device found at address 0x45  !
16:19:02.657 -> I2C device found at address 0x4A  !
16:19:02.657 -> I2C device found at address 0x50  !
16:19:02.657 -> I2C device found at address 0x55  !
16:19:02.657 -> I2C device found at address 0x5B  !
16:19:02.657 -> I2C device found at address 0x61  !
16:19:02.657 -> I2C device found at address 0x66  !
16:19:02.657 -> I2C device found at address 0x6C  !
16:19:02.657 -> Unknow error at address 0x73
16:19:02.657 -> I2C device found at address 0x79  !
16:19:02.690 -> **********************************
16:19:02.690 -> 
16:19:02.690 -> Scanning (SDA : SCL) - D3 : D0 - No I2C devices found
16:19:02.690 -> Scanning (SDA : SCL) - D3 : D1 - No I2C devices found
16:19:02.690 -> Scanning (SDA : SCL) - D3 : D2 - No I2C devices found
16:19:02.756 -> Scanning (SDA : SCL) - D3 : D4 - No I2C devices found
16:19:02.756 -> Scanning (SDA : SCL) - D3 : D5 - No I2C devices found
16:19:02.789 -> Scanning (SDA : SCL) - D3 : D6 - No I2C devices found
16:19:02.789 -> Scanning (SDA : SCL) - D3 : D7 - No I2C devices found
16:19:02.789 -> Scanning (SDA : SCL) - D4 : D0 - No I2C devices found
16:19:02.823 -> Scanning (SDA : SCL) - D4 : D1 - No I2C devices found
16:19:02.823 -> Scanning (SDA : SCL) - D4 : D2 - No I2C devices found
16:19:02.889 -> Scanning (SDA : SCL) - D4 : D3 - No I2C devices found
16:19:02.889 -> Scanning (SDA : SCL) - D4 : D5 - No I2C devices found
16:19:02.922 -> Scanning (SDA : SCL) - D4 : D6 - No I2C devices found
16:19:02.922 -> Scanning (SDA : SCL) - D4 : D7 - No I2C devices found
16:19:02.955 -> Scanning (SDA : SCL) - D5 : D0 - No I2C devices found
16:19:02.955 -> Scanning (SDA : SCL) - D5 : D1 - No I2C devices found
16:19:02.955 -> Scanning (SDA : SCL) - D5 : D2 - No I2C devices found
16:19:03.022 -> Scanning (SDA : SCL) - D5 : D3 - No I2C devices found
16:19:03.022 -> Scanning (SDA : SCL) - D5 : D4 - No I2C devices found
16:19:03.055 -> Scanning (SDA : SCL) - D5 : D6 - No I2C devices found
16:19:03.055 -> Scanning (SDA : SCL) - D5 : D7 - No I2C devices found
16:19:03.088 -> Scanning (SDA : SCL) - D6 : D0 - No I2C devices found
16:19:03.088 -> Scanning (SDA : SCL) - D6 : D1 - No I2C devices found
16:19:03.122 -> Scanning (SDA : SCL) - D6 : D2 - No I2C devices found
16:19:03.155 -> Scanning (SDA : SCL) - D6 : D3 - No I2C devices found
16:19:03.155 -> Scanning (SDA : SCL) - D6 : D4 - No I2C devices found
16:19:03.188 -> Scanning (SDA : SCL) - D6 : D5 - No I2C devices found
16:19:03.188 -> Scanning (SDA : SCL) - D6 : D7 - No I2C devices found
16:19:03.221 -> Scanning (SDA : SCL) - D7 : D0 - No I2C devices found
16:19:03.221 -> Scanning (SDA : SCL) - D7 : D1 - No I2C devices found
16:19:03.254 -> Scanning (SDA : SCL) - D7 : D2 - No I2C devices found
16:19:03.287 -> Scanning (SDA : SCL) - D7 : D3 - No I2C devices found
16:19:03.287 -> Scanning (SDA : SCL) - D7 : D4 - No I2C devices found
16:19:03.321 -> Scanning (SDA : SCL) - D7 : D5 - No I2C devices found
16:19:03.321 -> Scanning (SDA : SCL) - D7 : D6 - No I2C devices found

**Comment by xreef** [comment]
I think there is a noise on the shield the addres of the dht12 is 0x5c (as you can see in datasheet), but no result with this address, and I think It isn't connected to 20 i2c device.
Try remove the shield and relaunch the scanner.
I think something is broken.
Keep in touch.

**Comment by mwilfried** [comment]
Hello

I've checked the voltage on the 3,3v of each stage. 
First and second are OK, but the last where the DHT sensor is connected, I 've measured 2,0 volts.
I think you are right, there is Something not right.

I'm going to remove and try again , and in the same time try other hardware.

Thanks

**Comment by xreef** [comment]
Try external power source also.
Keep in touch.
Bye

**Comment by xreef** [comment]
Inactivity
