### ISSUE TITLE
working with second I2C bus for example with ESP32

### ISSUE THREAD

**Issue by issb-gh** [xreef/DHT12_sensor_library#5]
The ESP32 has two I2C buses. The first bus is mostly designed for an OLED and can also be used with the DHT12 or other sensor. The gpio pis are mostly SDA / SCL: 5/4 or 4/15.
The second I2C bus has the gpio pins SDA / SCL 21/22.
For DHT12 to work with this bus, some changes are needed in DHT12.cpp and DHT12.h.
The changes follow:

**Comment by issb-gh** [comment]
dht12.h:

#ifndef __AVR
	/**
	 * Additional parameter non tested for Arduino, Arduino very slow on software i2c
	 */
	DHT12(uint8_t sda, uint8_t scl);
	DHT12(uint8_t sda, uint8_t scl, uint8_t address);

///// changes for second i2c bus
        // for I2C second bus
	// Problem bei Uebergabe von sda u. scl
	DHT12(uint8_t addr, TwoWire *pWire);
	// deshalb dieser Konstruktor
	DHT12(uint8_t sda, uint8_t scl, uint8_t address, TwoWire *pWire);
// changes

#endif

...

private:
///// changes for second i2c bus
        // for I2C second bus
	TwoWire *_wire;

dht12.cpp:

DHT12::DHT12(void) {
	_wire = NULL;
}

DHT12::DHT12(uint8_t addressOrPin, bool oneWire) {
	_isOneWire = oneWire;
	if (oneWire) {
		_wire = NULL;
		_pin = addressOrPin;
		#ifdef __AVR
			_bit = digitalPinToBitMask(_pin);
			_port = digitalPinToPort(_pin);
		#endif
		_maxcycles = microsecondsToClockCycles(1000); // 1 millisecond timeout for
													  // reading pulses from DHT sensor.
		// Note that count is now ignored as the DHT reading algorithm adjusts itself
		// basd on the speed of the processor.

		DEBUG_PRINTLN("PIN MODE");
	} else {
		_wire = &Wire;
		_address = addressOrPin;
		DEBUG_PRINTLN("I2C MODE");
	}
}

// Is not good idea use other pin for i2c as standard on Arduino you can get lag.
// The lag happens when you choose "different pins", because you are then using a
// slow software emulation of the I2C hardware. The built in I2C hardware has fixed pin assignments.
#ifndef __AVR
	DHT12::DHT12(uint8_t sda, uint8_t scl) {
///// changes for second i2c bus
		_wire = &Wire;
		_isOneWire = false;
		_sda = sda;
		_scl = scl;
	}

	DHT12::DHT12(uint8_t sda, uint8_t scl, uint8_t address) {
///// changes for second i2c bus
		_wire = &Wire;
		_isOneWire = false;
		_sda = sda;
		_scl = scl;
		_address = address;
	}

///// changes for second i2c bus
	DHT12::DHT12(uint8_t address, TwoWire *pWire) {
		_wire = pWire;
		_isOneWire = false;
/*		
		sda = SCA (bus 0)!
		//_sda = sda;
		//_scl = scl;
*/
		_address = address;
	}
	DHT12::DHT12(uint8_t sda, uint8_t scl, uint8_t address, TwoWire *pWire) {
		_wire = pWire;
		_isOneWire = false;
		_sda = sda;
		_scl = scl;
		_address = address;
	}
// changes
#endif

...

void DHT12::begin() {
	_lastreadtime = -(MIN_ELAPSED_TIME + 1);
	if (_isOneWire) {
		// set up the pins!
		pinMode(_pin, INPUT_PULLUP);
		// Using this value makes sure that millis() - lastreadtime will be
		// >= MIN_INTERVAL right away. Note that this assignment wraps around,
		// but so will the subtraction.
		DEBUG_PRINT("Max clock cycles: ");
		DEBUG_PRINTLN(_maxcycles, DEC);
	} else if (_wire) {
		#ifndef __AVR
			_wire->begin(_sda, _scl);
		#else
//			Default pin for AVR some problem on software emulation
//			#define SCL_PIN _scl
// 			#define SDA_PIN _sda
			_wire->begin();
		#endif
		DEBUG_PRINT("I2C Inizialization: sda, scl: ");
		DEBUG_PRINT(_sda);
		DEBUG_PRINT(",");
		DEBUG_PRINTLN(_scl);
	}
}
...

and change all occurrences of _wire. with _wire->

would you include these changes in the master branch?

Greetings from Germany
Jens

**Comment by xreef** [comment]
Thanks for your feedback, I'll check It soon.
Thanks

**Comment by xreef** [comment]
Hi,
can you test the patch on TwoWire branch.
And can you add an example to add to the list of examples.
Thanks again Renzo

**Comment by xreef** [comment]
I add support for second i2c channel, please check my site on usage
https://www.mischianti.org/2019/01/01/dht12-library-en/
Thanks again for your support. Bye

**Comment by issb-gh** [comment]
excellent, thank you very much :-)
