### ISSUE TITLE
floating point measurment

### ISSUE THREAD

**Issue by tsknightstorm** [xreef/DHT12_sensor_library#6]
Hi xreef

In my case, I just got full numbers out of my sensor, no floating points. Maybe I miss understand something but is it true, that the library is right now not able to suport floating point?

The data Array ist defined as a int, with no floating points.
`uint8_t data[5];`

But one step up, we use floats for calculating with celcius and farenheid.
`float DHT12::readTemperature(bool scale, bool force) {
	float temperature = NAN;
...
`

Of corse calculating with floating points uses a big amount of CPU power, at least with no FPU in your CPU. Maybe it would make sense to take in the value, multiplie it by 10'000 and then calculate everything. Then we could take two read methods. One that returnes the value as a float again devided by 10'000 and one for more CPU optimiced usage with the int value aso the original value * 10'000.

Thanks for your work, support and maybe clearithing of my possible missunderstanding.

bests Night

**Comment by xreef** [comment]
Hi tsknightstorm,
thanks to contact me, I choice that solution to be compliant with Adafruit DHT library, when we do a library It's important to be compliant and It's also important to simplify the work to the people.
It's a features that can be interesting, if you doing a pull request I'm going to check It better.
Thank again Renzo

**Comment by tsknightstorm** [comment]
Hmm I see your point. So for now it is impossible to have some floating values of the temperatures? Wouldn't it be possible to add this functionality with a extra methode? Then it would be compliant and more flexible too.

**Comment by xreef** [comment]
I think there is a misunderstanding, temperature is already a floating point value.

**Comment by tsknightstorm** [comment]
In my usecase I just get 1°C steps without any floating points (always 0). It makes also sense if I go into the lib. The return value is float, but one step more in there is the uint8_t data[5] array. Maybe I do some miss use of your library?

**Comment by xreef** [comment]
When did you download the library?? You have the last version??

**Comment by tsknightstorm** [comment]
I have the Version 0.9.0. Maybe downloaded a year ago. Should I update it? --> a of corse I should :-P. I will try it as soon as possible.

**Comment by tsknightstorm** [comment]
ok the mentioned data[] is also in uint8_t (DHT.h line 168). With that it should not be possible to get a floating point result.

But I do not exaclty understand the calculation in DHT.c line 404. Maybe there is a voltage measurment calculated in a floating temp? Then it should have floating points.

sorry for disturbing you with my mess.

**Comment by xreef** [comment]
The sensor work like an IC, we communicate with It using a protocol that is defined in the datasheet, the packet have a specified format, and when return we must converte the byte in a number as defined.
Bye Renzo
