### ISSUE TITLE
Small patch to make it compile with stm32duino / bluepill

### ISSUE THREAD

**Issue by mean00** [xreef/DHT12_sensor_library#7]
Hi
Crude patch below  so that it compiles with a bluepill running stm32duino
Not pretty, but it works tm
The only other thing needed is to define SDA & SCL but that can be easily done from outside

[stm32duino_bluepill.diff.txt](https://github.com/xreef/DHT12_sensor_library/files/3705850/stm32duino_bluepill.diff.txt)

**Comment by xreef** [comment]
Hi, sorry if I couldn't answer you sooner.
Please can you try my patch to your problem.
Thanks Renzo

**Comment by mean00** [comment]
Thank you
I does compile :) (could not test it yet)
The last one missing is setting (default) SDA/SCL to PB7/PB6 on bluepill and it's all fine
I dont mind because i'm not using the arduino build system so i can override it easily
but others may be bothered

**Comment by xreef** [comment]
Hi, It's strange I used the SDA and SCL standard global variable to set It.
Can you check what kind of value you have on SDA and SCL?
Thanks

**Comment by mean00** [comment]
Hi
After looking into it, SDA and SCL are only defined when including SoftWire (i.e. soft SPI/I2C)
When using Wire (Hardware SPI/I2C) they are not defined at all, hence the problem
#ifdef _ _ STM32F1 _ _
#ifndef SDA 
  #define SDA PB7
  #define SCL PB6
#endif
#endif 
might do the trick ?

**Comment by xreef** [comment]
Hi
Try the last commit.
Thanks

**Comment by mean00** [comment]
Hi
Sorry for the delay
Almost there : it's #ifdef _ _ STM32F1 _ _ and not #ifdef STM32F1
(i.e. underscore underscore STM32F1 underscore underscore)
Aprt from that : :)

**Comment by xreef** [comment]
Hi
I push this change.
Try now Thanks.

**Comment by mean00** [comment]
Perfect
Thanks !

**Comment by xreef** [comment]
Thanks for your support.
