### ISSUE TITLE
SDA and SCL pins

### ISSUE THREAD

**Issue by Jxid** [xreef/DHT12_sensor_library#8]
Thanks for library.
But i have an issue.
I got an DHT12 sensor and i tried to connect it to and ESP8266.
Althought the example says to connect SDA to D1 and SCL to D2 it never worked.
So i connect SDL to D1 and SDA to D2                           
Then the sensor worked fine.

**Comment by xreef** [comment]
Thanks, I fixed It.
Thanks again Renzo
